#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'lxc',
  :git => 'https://github.com/hw-cookbooks/lxc.git',
  :ref => 'develop'

cookbook 'docker'
cookbook 'ruby_installer'
